// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnujIsGECIbiWAygMds-USaNvFEnfEa3U',
    appId: '1:148790667634:web:a83a9f337998a9287ed5eb',
    messagingSenderId: '148790667634',
    projectId: 'aravind-aeih',
    authDomain: 'aravind-aeih.firebaseapp.com',
    storageBucket: 'aravind-aeih.appspot.com',
    measurementId: 'G-4503Q1ML5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9_dPw0QcQ_CsUwJupqH-9zHZWHHqRv6U',
    appId: '1:148790667634:android:72790cdce77b78417ed5eb',
    messagingSenderId: '148790667634',
    projectId: 'aravind-aeih',
    storageBucket: 'aravind-aeih.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYE0c7scDKdUjfuvPb81Zxr224aJT759g',
    appId: '1:148790667634:ios:5a59d8b0ea4ee4c47ed5eb',
    messagingSenderId: '148790667634',
    projectId: 'aravind-aeih',
    storageBucket: 'aravind-aeih.appspot.com',
    iosBundleId: 'com.example.dhrishtiPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYE0c7scDKdUjfuvPb81Zxr224aJT759g',
    appId: '1:148790667634:ios:5a59d8b0ea4ee4c47ed5eb',
    messagingSenderId: '148790667634',
    projectId: 'aravind-aeih',
    storageBucket: 'aravind-aeih.appspot.com',
    iosBundleId: 'com.example.dhrishtiPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnujIsGECIbiWAygMds-USaNvFEnfEa3U',
    appId: '1:148790667634:web:508ac9b478c4fa897ed5eb',
    messagingSenderId: '148790667634',
    projectId: 'aravind-aeih',
    authDomain: 'aravind-aeih.firebaseapp.com',
    storageBucket: 'aravind-aeih.appspot.com',
    measurementId: 'G-F96441KDZQ',
  );
}
