// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgOzqb6mwfXescCGDPlVhidecFZPtW2BI',
    appId: '1:346946868875:web:a1bd0e0c474d00a535668e',
    messagingSenderId: '346946868875',
    projectId: 'aravindaeih',
    authDomain: 'aravindaeih.firebaseapp.com',
    storageBucket: 'aravindaeih.appspot.com',
    measurementId: 'G-D6DJ0TS25S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC93qfHJdtDxhiw-1yOPnKSOLCkO71RvuY',
    appId: '1:346946868875:android:3be04001fb1304a335668e',
    messagingSenderId: '346946868875',
    projectId: 'aravindaeih',
    storageBucket: 'aravindaeih.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEJXJlteJvpYOtKSjQIMnH1XGNSlysu8E',
    appId: '1:346946868875:ios:5d77550d524b60d835668e',
    messagingSenderId: '346946868875',
    projectId: 'aravindaeih',
    storageBucket: 'aravindaeih.appspot.com',
    iosBundleId: 'com.example.dhrishtiPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEJXJlteJvpYOtKSjQIMnH1XGNSlysu8E',
    appId: '1:346946868875:ios:5d77550d524b60d835668e',
    messagingSenderId: '346946868875',
    projectId: 'aravindaeih',
    storageBucket: 'aravindaeih.appspot.com',
    iosBundleId: 'com.example.dhrishtiPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgOzqb6mwfXescCGDPlVhidecFZPtW2BI',
    appId: '1:346946868875:web:7cd867d91bff10eb35668e',
    messagingSenderId: '346946868875',
    projectId: 'aravindaeih',
    authDomain: 'aravindaeih.firebaseapp.com',
    storageBucket: 'aravindaeih.appspot.com',
    measurementId: 'G-M9P1PHSC5Z',
  );
}
